name = "war"
compatibility_date = "2024-09-14"
compatibility_flags = [ "nodejs_compat" ]

# [[kv_namespaces]]
# binding = "KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[vars]
# CALLBACK_URL = "http://localhost:3000"
CALLBACK_URL = "https://github.com/malkiii#start-of-content"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
